### ISSUE TITLE
Demo and missed detection

### ISSUE THREAD

**Issue by hz-ants** [duzw9311/CFPT#5]
Thanks to the great work of the author, there are two questions that make me wonder: 1. how to load other arbitrary pictures or videos with the existing pre training model? Do you want to use demo.py in the example 2. as shown in the red circle in the figure below, I can't detect it with R18 and R101. Is there any improvement method?
![001](https://github.com/user-attachments/assets/8acdcb75-8068-46a4-a6b6-60f01ea700b6)

**Comment by duzw9311** [comment]
Thank you for your attention. 
1. You can use the Python script in the folder named "demo" provided by the MMDetection toolbox to perform inference on the specified images and videos. 
2. We provided the models based on RetinaNet training for 12 epochs and reported the test results for the entire VisDrone dataset. To achieve better results, you could adjust the confidence threshold, modify the model hyperparameters, train for additional epochs, or use a more advanced baseline model.
